/** Central list of API endpoint paths (relative to the client baseURL). */
export const endpoints = {
  auth: {
    login: "/auth/login",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
    logoutAll: "/auth/logout-all",
    me: "/auth/me",
    resetPassword: "/auth/reset-password",
  },
  projects: {
    list: "/projects",
    options: "/projects/options",
    create: "/projects",
    detail: (projectId: string) => `/projects/${projectId}`,
    update: (projectId: string) => `/projects/${projectId}`,
    delete: (projectId: string) => `/projects/${projectId}`,
    priority: (projectId: string) => `/projects/${projectId}/priority`,
    status: (projectId: string) => `/projects/${projectId}/status`,
    importPreview: "/projects/import/preview",
    import: "/projects/import",
  },
  users: {
    list: "/users",
    detail: (userId: string) => `/users/${userId}`,
    invite: "/users/invites",
    invites: "/users/invites",
    resendInvite: (inviteId: string) => `/users/invites/${inviteId}/resend`,
    revokeInvite: (inviteId: string) => `/users/invites/${inviteId}`,
    update: (userId: string) => `/users/${userId}`,
    delete: (userId: string) => `/users/${userId}`,
    resetLink: (userId: string) => `/users/${userId}/reset-link`,
  },
  invites: {
    detail: (token: string) => `/invites/${token}`,
    accept: (token: string) => `/invites/${token}/accept`,
  },
  profile: {
    me: "/profile",
    update: "/profile",
    avatar: "/profile/avatar",
    passwordOtp: "/profile/password/otp",
    password: "/profile/password",
  },
  integrations: {
    discordTestUser: "/integrations/discord/test-user",
  },
  settings: {
    workspace: "/settings/workspace",
    emailConnector: "/settings/email-connector",
    googleConnect: "/settings/email-connector/google/connect",
    googleDisconnect: "/settings/email-connector/google/disconnect",
    emailConnectorTest: "/settings/email-connector/test",
    emailConnectorTestSend: "/settings/email-connector/test-send",
    aiPrompt: (promptKey: string) => `/settings/ai-prompts/${promptKey}`,
  },
  notifications: {
    list: "/notifications",
    unreadCount: "/notifications/unread-count",
    readAll: "/notifications/read-all",
    markRead: (notificationId: string) => `/notifications/${notificationId}/read`,
    settings: "/notifications/settings",
    test: "/notifications/test",
    discordTest: "/notifications/discord/test",
    emailTest: "/notifications/email/test",
    runDailySummary: "/notifications/jobs/daily-summary/run",
    runPreShift: "/notifications/jobs/pre-shift/run",
    runWeeklyDigest: "/notifications/jobs/weekly-digest/run",
    create: "/notifications",
  },
  activityLogs: {
    users: "/activity-logs/users",
    userOptions: "/activity-logs/users/options",
    websites: "/activity-logs/websites",
    websiteOptions: "/activity-logs/websites/options",
  },
  websiteUsers: {
    list: "/website-users",
    options: "/website-users/options",
    create: "/website-users",
    update: (credentialId: string) => `/website-users/${credentialId}`,
    delete: (credentialId: string) => `/website-users/${credentialId}`,
    reveal: (credentialId: string) => `/website-users/${credentialId}/reveal`,
    copyPackage: (credentialId: string) => `/website-users/${credentialId}/copy-package`,
    importPreview: "/website-users/import/preview",
    import: "/website-users/import",
  },
  issues: {
    list: "/issues",
    options: "/issues/options",
    create: "/issues",
    detail: (issueId: string) => `/issues/${issueId}`,
    update: (issueId: string) => `/issues/${issueId}`,
    status: (issueId: string) => `/issues/${issueId}/status`,
    delete: (issueId: string) => `/issues/${issueId}`,
    applications: (issueId: string) => `/issues/${issueId}/applications`,
    application: (issueId: string, applicationId: string) =>
      `/issues/${issueId}/applications/${applicationId}`,
  },
  tasks: {
    list: "/tasks",
    my: "/tasks/my",
    assignees: "/tasks/assignees",
    uploads: "/tasks/uploads",
    create: "/tasks",
    detail: (taskId: string) => `/tasks/${taskId}`,
    update: (taskId: string) => `/tasks/${taskId}`,
    status: (taskId: string) => `/tasks/${taskId}/status`,
    delete: (taskId: string) => `/tasks/${taskId}`,
    move: "/tasks/move",
    approve: (taskId: string) => `/tasks/${taskId}/approve`,
    reject: (taskId: string) => `/tasks/${taskId}/reject`,
  },
  notes: {
    list: "/notes",
    create: "/notes",
    update: (noteId: string) => `/notes/${noteId}`,
    delete: (noteId: string) => `/notes/${noteId}`,
  },
  ai: {
    organizeTask: "/ai/tasks/organize",
  },
  websiteHealth: {
    list: "/website-health",
    capabilities: "/website-health/capabilities",
    website: (websiteId: string) => `/website-health/websites/${websiteId}`,
    history: (websiteId: string) => `/website-health/websites/${websiteId}/history`,
    profile: (websiteId: string) => `/website-health/websites/${websiteId}/profile`,
    formTest: (websiteId: string) => `/website-health/websites/${websiteId}/forms/test`,
    scans: "/website-health/scans",
    scan: (scanId: string) => `/website-health/scans/${scanId}`,
    cancel: (scanId: string) => `/website-health/scans/${scanId}/cancel`,
    retry: (scanId: string) => `/website-health/scans/${scanId}/retry`,
    pages: (scanId: string) => `/website-health/scans/${scanId}/pages`,
    report: (scanId: string) => `/website-health/scans/${scanId}/report`,
    finding: (findingId: string) => `/website-health/findings/${findingId}`,
    checklists: "/website-health/checklists",
    uploads: "/website-health/uploads",
    formVerifications: (websiteId: string) =>
      `/website-health/websites/${websiteId}/form-verifications`,
    formVerification: (websiteId: string, formKey: string) =>
      `/website-health/websites/${websiteId}/form-verifications/${encodeURIComponent(formKey)}`,
    designVerifications: (websiteId: string) =>
      `/website-health/websites/${websiteId}/design-verifications`,
    designVerification: (websiteId: string, pageKey: string) =>
      `/website-health/websites/${websiteId}/design-verifications/${encodeURIComponent(pageKey)}`,
  },
  wordpressConnector: {
    detail: (websiteId: string) => `/connectors/wordpress/${websiteId}`,
    pairingCode: (websiteId: string) => `/connectors/wordpress/${websiteId}/pairing-code`,
    refresh: (websiteId: string) => `/connectors/wordpress/${websiteId}/refresh`,
  },
  agent: {
    oauthAuthorize: "/agent/oauth/authorize",
    grants: "/agent/grants",
    grant: (grantId: string) => `/agent/grants/${grantId}`,
  },
  clientLogs: {
    templates: "/client-logs/templates",
    template: (templateId: string) => `/client-logs/templates/${templateId}`,
    templateStages: (templateId: string) => `/client-logs/templates/${templateId}/stages`,
    templateStage: (templateId: string, stageId: string) => `/client-logs/templates/${templateId}/stages/${stageId}`,
    templateReorder: (templateId: string) => `/client-logs/templates/${templateId}/reorder`,
    overview: "/client-logs/overview",
    assignableUsers: "/client-logs/assignable-users",
    projectStages: (projectId: string) => `/client-logs/projects/${projectId}/stages`,
    applyTemplate: (projectId: string) => `/client-logs/projects/${projectId}/apply-template`,
    launchReadiness: (projectId: string) => `/client-logs/projects/${projectId}/launch-readiness`,
    resetProject: (projectId: string) => `/client-logs/projects/${projectId}/client-logs`,
    stage: (stageId: string) => `/client-logs/stages/${stageId}`,
    stageReorder: (projectId: string) => `/client-logs/projects/${projectId}/stages/reorder`,
    stageTasks: (stageId: string) => `/client-logs/stages/${stageId}/tasks`,
    stageTaskLink: (stageId: string) => `/client-logs/stages/${stageId}/tasks/link`,
    meetingsImport: "/client-logs/meetings/import",
    projectMeetings: (projectId: string) => `/client-logs/projects/${projectId}/meetings`,
    meetingActionConfirm: (actionId: string) => `/client-logs/meeting-actions/${actionId}/confirm`,
    meetingActionReject: (actionId: string) => `/client-logs/meeting-actions/${actionId}/reject`,
  },
} as const;
